0no-co/GraphQLSP

.changeset/five-dancers-refuse.md
example/src/index.generated.ts
example/tsconfig.json
example/yarn.lock
package.json
pnpm-lock.yaml
src/getSchema.ts
src/index.ts

Currently we support specifying a `.json` and `.graphql` file and will use that as the schema, however a lot of people don't have the schema locally. This PR adds support for fetching the schema from a remote source, this delays the LSP working for the duration of the fetch request.
Resolves #12

feat: resolve introspection from url

---

.changeset/olive-jokes-drum.md
src/index.ts
src/utils.ts

Currently we have a slight race condition, in terms of writing to the TypeScript file. We check whether the user saved to kick off type-generation and when the async process for type-generation completes we write to the file, however our user could have performed additional changes in this small timeframe, this is why we have introduced an additional dirty check in the `.then` of our type-generation.
fixes https://github.com/0no-co/GraphQLSP/issues/25

fix: perform dirty check after async generation completes

---

.changeset/grumpy-toes-serve.md
src/index.ts

Resolves https://github.com/0no-co/GraphQLSP/issues/20
This will use the TS.LabelDetails to show some information alongside the `fieldName` or `fragmentName`. For suggested `FragmentSpread` insertions we will display the `typeCondition` while for fields we will display the `documentation` found in the schema _or_ the associated field-type.

feat: display documentation for fields and fragments

---

.changeset/proud-trainers-switch.md
example/src/index.generated.ts
example/src/index.ts
src/index.ts
src/utils.ts

We used to suggest fragment-spreads for every definition even if we weren't residing under the correct type.
Fixes #30

fix: only suggest fragment spreads within the correct type-bounds

---

test/e2e/fixture-project/fixtures/rename.ts
test/e2e/rename.test.ts
test/e2e/util.ts

Added e2e for renaming an operation name.
I added this as a new file so the tests can run in parallel.
// does this require a changeset?

Add e2e test for renaming an operation name

---

.changeset/five-monkeys-ring.md
.github/workflows/release.yaml
packages/graphqlsp/package.json

This now uses [provenance](https://docs.npmjs.com/generating-provenance-statements) to prove that this was a good deploy.

chore(workspace): publish with provenance

---

.changeset/unlucky-geese-double.md
package.json
packages/graphqlsp/src/autoComplete.ts
test/e2e/graphqlsp.test.ts
test/e2e/server.ts

Resolves https://github.com/0no-co/GraphQLSP/issues/16
When autocomplete is triggered in the following scenarios:
* field names
* input vars names
* fragment spreads
The LSP will no longer recommend members which are already present 🎉 
Demo: https://www.loom.com/share/3d342956e5234f69ba962dfdd8ab2d15
**Note: I do have unit tests for this code, but getting some error about duplicate `graphql` versions running in the test, so trying to fix that.**
I'll try contributing this change into the graphiql repo for the language service package, but as this change current behavior, it will probably take a while to get merged (in the case that it does get accepted 😅). In the case it does get merged, I'll remove some of the code added here as it won't longer be needed (some parts of it still will be …

Do not suggest fields/fragments/input vars that are already present.

---

.changeset/shaggy-ravens-train.md
packages/graphqlsp/src/index.ts

When performing `getSemanticDiagnostics` with a general TS-error in the file we would offset wrongly as we perform the original before the lsp ones.

fix wrong offsets by altering the source-file after doing original diag

---

.changeset/nervous-shoes-cheer.md
packages/graphqlsp/README.md
packages/graphqlsp/src/diagnostics.ts
packages/graphqlsp/src/graphql/getSchema.ts
packages/graphqlsp/src/index.ts

This option is mainly because there are a few issues with type-generation at the moment especially when there's multiple untyped operations within a source-file

add option to disable type generation

---

.changeset/hungry-hairs-draw.md
packages/graphqlsp/src/ast/resolve.ts
packages/graphqlsp/src/autoComplete.ts
packages/graphqlsp/src/diagnostics.ts
packages/graphqlsp/src/graphql/generateTypes.ts
packages/graphqlsp/src/quickInfo.ts

Partially resolves #72 
This avoids us polluting the LSP with diagnostics that go outside of the AST Node Range. An ideal solution here would be to indicate these on the `FragmentDefinition` itself, or TypeScript providing a way to tell us about a nested error.
This PR partially resolves the problem but introduces a new one where if folks add identifiers to the start of their document that we will convey the wrong information, however this is currently also present... After experimenting 😅 
Ideally during `resolve` we will start returning 
- the full text
- definition --> text
- ranges of definition --> text
This will allow us to translate and combine diagnostics effectively

avoid giving diagnostics for stuff falling out of the node-range

---

.changeset/lovely-months-type.md
packages/example/src/Pokemon.ts
packages/graphqlsp/src/diagnostics.ts
test/e2e/fixture-project/fixtures/rename-complex.ts
test/e2e/generate-types.test.ts

start looking for replacements at the start of our node

---

.changeset/cuddly-lobsters-return.md
packages/example/src/Pokemon.ts
packages/example/src/index.generated.ts
packages/example/src/index.ts
packages/graphqlsp/README.md
packages/graphqlsp/src/graphql/getSchema.ts
packages/graphqlsp/src/index.ts
pnpm-lock.yaml

Main reasoning for allowing it to be in JSON is that development are often not real secrets and when `http` is leveraged this seems redundant for the env. When it's really needed folks can opt into the file-based approach.
Resolve #85

allow specifying headers to get introspection

---

.changeset/small-pots-boil.md
packages/example/src/index.generated.ts
packages/example/src/index.ts
packages/graphqlsp/src/diagnostics.ts

When the template-expression is not caught in a variable i..e when the parent is an expression statement we have to add 2
fixes #93

catch expression statements correctly

---

.changeset/empty-planes-behave.md
packages/graphqlsp/src/diagnostics.ts

When setting `shouldCheckForColocatedFragments: false` it will still fall back to `true` with the OR `||` check.

fix `shouldCheckForColocatedFragments` option

---

.changeset/fresh-grapes-melt.md
packages/graphqlsp/src/ast/resolve.ts

If someone decided to import from `x.generated` they would be importing a parsed AST-node which would fail resolution, this now works like interpolating stringified fragments.
Resolves #102

fix(template-resolution): resolve interpolated parsed fragments

---

README.md
packages/graphqlsp/README.md

Resolves https://github.com/0no-co/GraphQLSP/issues/128

docs: document lack of syntax highlighting

---

.changeset/hip-poems-remain.md
packages/graphqlsp/src/autoComplete.ts
packages/graphqlsp/src/quickInfo.ts

Resolves #111
fixes #127
fixes #130 
This introduces two changes, first we use our internal suggestions algorithm which filters out fragments and fields that are already used (unless using an alias). Secondly it decrements the starting token for the col to improve suggestions for narrow spacing i.e. `queryField()` and `fragment x on Y {}`

feat: use internal suggestions

---

.changeset/khaki-clouds-marry.md
packages/example-external-generator/src/index.tsx
packages/example/src/index.ts
packages/graphqlsp/src/diagnostics.ts

Resolves #142
Currently didn't opt to add a setting for it yet as it felt overkill 😅

fix(diag): avoid erroring on known client side directives

---

.changeset/bright-news-agree.md
packages/example/src/Pokemon.ts
packages/example/src/index.ts
packages/graphqlsp/src/quickInfo.ts
test/e2e/client-preset.test.ts
test/e2e/combinations.test.ts
test/e2e/graphqlsp.test.ts

Resolve #124 
There are probably more possible improvements, looking at what it produces from an urql TSDoc...
```json
"body": {
"kind": "alias",
"kindModifiers": "declare",
"start": {
"line": 39,
"offset": 1
},
"end": {
"line": 39,
"offset": 13
},
"displayString": "(alias) createClient(opts: ClientOptions): Client\nimport createClient",
"documentation": [
{
"text": "Accepts `ClientOptions` and creates a `Client`.",
"kind": "text"
}
],
"tags": [
{
"name": "param",
"text": [
{
"text": "opts",
"kind": "parameterName"
},
{
"text": " ",
"kind": "space"
},
{
"text": "- A ",
"kind": "text"
},
{
"text": "{@link ",
"kind": "link"
},
{
"text": "ClientOptions",
"kind": "linkName",
"target": {
"file": "/Users/jovi/Documents/SideProjects/GraphQLSP/node_modules/.pnpm/@urql+core@3.2.2_graphql@16.8.1/nod …
```

fix: adjust documentation display

---

.changeset/mean-news-unite.md
packages/example-external-generator/src/index.tsx
packages/example-external-generator/tsconfig.json
packages/graphqlsp/src/ast/index.ts
packages/graphqlsp/src/autoComplete.ts
packages/graphqlsp/src/checkImports.ts
packages/graphqlsp/src/diagnostics.ts
test/e2e/client-preset.test.ts
test/e2e/fixture-project-client-preset/fixtures/fragment.ts
test/e2e/fixture-project-client-preset/fixtures/unused-fragment.ts
test/e2e/fixture-project-client-preset/tsconfig.json

This adds support for searching the imports for fragments, then it will check all the found fragments whether they are used in the GraphQL documents of the file you are working in. When we find unused fragments we will warn the user.
Resolves #153

feat: add missing fragment spread warnings

---

.changeset/tough-birds-brush.md
packages/example-tada/introspection.ts
packages/example-tada/tsconfig.json
packages/graphqlsp/package.json
packages/graphqlsp/src/graphql/getSchema.ts
pnpm-lock.yaml

This allows us to save to a filename directly as part of the `tadaOutputLocation` format.
When a directory is given the `introspection.d.ts` filename is appended and a `d.ts`-type output is created. When a filename is given, it checks for `.ts` or `.d.ts` and uses the corresponding format.
Depending on which format is used, the output will differ slightly. The `.d.ts` file format will aim to declare the introspection type directly into `gql.tada`, minimising the amount of setup that's needed.
When the `.ts` format is used, only a variable is exported from it for the introspection, as before. To help with setup steps, TSDocs are added to the output that show the user how to use the output files.
- Reformat `loadSchema` to extract identical code paths
- Reconcile saving introspections to …

feat: Allow tadaOutputLocation to contain file target and switch output modes

---

.changeset/new-feet-travel.md
packages/example-tada/introspection.ts
packages/graphqlsp/src/fieldUsage.ts
test/e2e/fixture-project-client-preset/tsconfig.json

In tada when doing
```js
export const Pokemon = ({ data }: { data: FragmentOf<typeof Fragment>}) => {
```
We would analyse references on Pokemon for the fragment, to counter act this we'll check all field usage in total across references

fix(field usage): avoid checking usage multiple times

---

.changeset/wild-lizards-fry.md
packages/graphqlsp/src/diagnostics.ts
test/e2e/server.ts

Stop caching diagnostics for fragment imports and field-usage as these can be controlled externally, only caching the source-texts diagnostics

fix: avoid diagnostics for fragment imports and field-usage

---

.changeset/wise-mangos-kick.md
packages/example-tada/src/index.tsx
packages/example-tada/tsconfig.json
packages/graphqlsp/package.json
packages/graphqlsp/src/diagnostics.ts
packages/graphqlsp/src/fieldUsage.ts
pnpm-lock.yaml

This also made me realise that `.map/...` the built-in array methods when used without fragmentRefs will indicate unused stuff... so we might need to add a method to support crawling new references produced by these functional methods... Same for a for/while loop I reckon but that will be less present in most apps
EDIT: added support for built-in methods in https://github.com/0no-co/GraphQLSP/pull/177/commits/c5b1e9e4825bc212e7e634793a3144b1cd8dd9ad

fix(field-usage): support Array.at and non-null-expressions

---

.changeset/honest-hairs-rule.md
packages/graphqlsp/src/fieldUsage.ts

When we have a query like the following
```graphql
query {
pokemon(id: 1) { id name }
pokemons { id fleeRate }
}
```
and we perform
```ts
const Pokemons = () => {
const [result] = useQuery({
query: PokemonQuery,
});
return result.data.pokemons.map(pokemon => pokemon.fleeRate)
}
```
Then it will see `pokemon` the variable inside our function closure as an allowed field due to `Query.pokemon` this PR fixes that by refining our search algorithm to only include valid built paths.

fix(field-usage): overlapping variable names

---

.changeset/hot-icons-fetch.md
packages/graphqlsp/src/graphql/getSchema.ts

This exports `export type introspection` in `d.ts` files so it can be reused.
This is important because it's much more performant on huge schemas than a `typeof introspection`, so providing this alternative is really valuable.

fix: Export introspection type in d.ts output

---

.changeset/orange-dodos-grab.md
packages/graphqlsp/package.json
pnpm-lock.yaml

`@urql/introspection@1.0.3` fixes redundant `Any` types being added to the introspection output. These weren't needed with the options we passed into `minifyIntrospectionQuery`, but were added by the utility anyway.

fix: Upgrade to @urql/introspection@1.0.3

---

.changeset/yellow-pianos-explode.md
packages/graphqlsp/src/graphql/getSchema.ts

This adds a small preamble to output files:
```js
/* eslint-disable */
/* prettier-ignore */
```
...to disable Prettier and ESLint on them automatically.

fix: Add prettier/eslint disable comments to output

---

.changeset/angry-eyes-occur.md
packages/example-tada/introspection.ts
packages/example-tada/src/Pokemon.tsx
packages/example-tada/src/index.tsx
packages/graphqlsp/src/ast/index.ts

When we were using `fields.pokemon` for instance we wouldn't immediately get to an identifier nor would the resulting reference be a variable-assignment.
We're still missing cases like `[...fragments]` and `[...Object.values(fragments)]`, ... but I wouldn't consider those great options and will tackle them when they pop up.
Resolves #201

feat(lsp): support prop assignment

---

.changeset/tiny-snails-raise.md
packages/graphqlsp/src/fieldUsage.ts

Resolves #229
Resolves #224
Previously, the crawler tracking unused fields wasn't using the type checker to assist with its search of GraphQL data variables. This meant that we were carefully limiting the amount of cases we'd support.
However, as it's hard for us to account for every GraphQL client (that supports `TypedDocumentNode`) with every possible API (not just hooks, for example, or nested functions inside hooks), we now attempt to find a more general solution.
This PR, when merged, adds a new primary method of discovering where a GraphQL document is used. This new method finds variables in-scope at the point the document is referenced and then matches the type of these variables against the type of the document.
When a match is found, we then know to start tracking field usage for …

feat: Expand tracking unused fields support to more cases

---

.changeset/olive-trains-love.md
packages/graphqlsp/src/fieldUsage.ts

The `visit` code that was computing field paths of a given GraphQL document wasn't handling field aliases before, causing all field aliases to be marked as unused in TypeScript code consuming data.
```ts
export const PokemonFields = graphql(/* GraphQL */`
fragment pokemonFields on Pokemon {
_name: name # marked as unused even if _name is accessed
weight { 
minimum
}
}
`);
```
- Include `field.alias.value` when computing all paths of a document

fix: Fix unused fields detection not respecting field aliases

---

.changeset/loud-moles-wait.md
packages/graphqlsp/src/graphql/getSchema.ts

This makes it less prone to needing cleanup work as we now should just issue one new poll-attempt per func-invocation

chore: change to setTimeout

---

.changeset/cool-elephants-invent.md
packages/graphqlsp/package.json
packages/graphqlsp/src/graphql/getSchema.ts
packages/graphqlsp/src/index.ts
pnpm-lock.yaml
tsconfig.json

We have seen annoyance when extending a `tsconfig` to get the correct path to resolve the schema or introspection json from. This addresses that by following the extension chain

chore: resolve schema from alternative rootDirectories

---

.changeset/witty-pigs-approve.md
packages/graphqlsp/src/graphql/getSchema.ts

Fixes https://github.com/0no-co/GraphQLSP/issues/265
This adds support for finding the extended `tsconfig` and by extension the `schema` in `node_modules`. We might need to add a `createRequire` snippet in the ESM bundle as `import.meta.resolve` still seems unstable.

fix(lsp): support node_modules in tsconfig resolution

---

.changeset/eighty-seahorses-unite.md
package.json
packages/graphqlsp/package.json
pnpm-lock.yaml

See: https://github.com/0no-co/gql.tada/pull/156
This marks `typescript` as a peer dependency so it can be deduplicated with `@gql.tada/internal`.

chore: Add peerDependencies on TypeScript

---

packages/example-tada/src/index.tsx
packages/graphqlsp/src/api.ts
packages/graphqlsp/src/ast/index.ts
packages/graphqlsp/src/diagnostics.ts
packages/graphqlsp/src/index.ts
packages/graphqlsp/src/persisted.ts
pnpm-lock.yaml
test/e2e/fixture-project-tada/introspection.d.ts

Related to https://github.com/0no-co/gql.tada/issues/77
This is an initial PR to support `graphql.persisted` as an LSP target, the goal is to provide semantic diagnostics for:
- missing type-argument
- erroneous type-argument (no reference found for instance)
- missing hash argument
Another goal is to provide a code-action to generate the `hash` associated with this invocation where we'll check whether there is a missing, or missmatched hash present and then present the user with a prompt to generate a SHA256 for the document we have found through following the TypeArgument.
We could also provide diagnostics for missmatched arguments, i.e. when the hash isn't correct compared to the hash we calculate for the referenced document but because we want to allow for ease I opted out of that. …

feat: initial support for `graphql.persisted`

---

.changeset/cuddly-needles-glow.md
packages/example-tada/src/index.tsx
packages/graphqlsp/src/api.ts
packages/graphqlsp/src/diagnostics.ts
packages/graphqlsp/src/persisted.ts
pnpm-lock.yaml

We have a follow up planned where we leverage the typeChecker like https://github.com/0no-co/gql.tada/blob/main/packages/cli-utils/src/commands/cache.ts#L70-L91 to adjust the routing of `ts.identifier` and `ts.typeQuery` to the document.

feat: support first argument in graphql.persisted

---

.changeset/selfish-adults-heal.md
packages/graphqlsp/src/graphql/getSchema.ts

This inserts the swap-writing that we do in the `gql.tada` CLI now into the GraphQLSP writing of the tada output file.

fix: Swap-write `gql.tada` output file instead of writing to it directly

---

.changeset/plenty-lizards-explain.md
packages/graphqlsp/src/diagnostics.ts

Should we also go from Warn --> Info?
Resolves https://github.com/0no-co/GraphQLSP/issues/252

chore(core): switch error message for missing-operation-name

---

.changeset/six-chefs-hammer.md
packages/graphqlsp/src/diagnostics.ts

Fixes https://github.com/0no-co/gql.tada/issues/217
The global regex was aggregating state hence when two directives popped up in different documents this failed.

fix(diag): directive miss report with multiple documents

---

.changeset/many-nails-wait.md
packages/graphqlsp/src/diagnostics.ts
packages/graphqlsp/src/persisted.ts

During diagnostics when we see a prefix of `sha256` we can assume that we generated the hash, this means we can verify whether it's up to date. This adds a warn diagnostic for persisted-operations and warns you when the hash is up to date with the document.

feat(diagnostics): validate up to date hash

---

.changeset/light-penguins-explain.md
packages/example-tada/introspection.d.ts
packages/example-tada/package.json
packages/example-tada/tsconfig.json
packages/graphqlsp/package.json
packages/graphqlsp/src/ast/index.ts
packages/graphqlsp/src/autoComplete.ts
packages/graphqlsp/src/checkImports.ts
packages/graphqlsp/src/diagnostics.ts
packages/graphqlsp/src/graphql/getSchema.ts
packages/graphqlsp/src/index.ts
packages/graphqlsp/src/persisted.ts
packages/graphqlsp/src/quickInfo.ts
pnpm-lock.yaml

See: https://github.com/0no-co/gql.tada/issues/248

feat(core): add support for multiple schemas

---

.changeset/young-phones-search.md
packages/graphqlsp/src/ast/checks.ts
packages/graphqlsp/src/ast/index.ts
packages/graphqlsp/src/ast/resolve.ts
packages/graphqlsp/src/ast/token.ts
packages/graphqlsp/src/autoComplete.ts
packages/graphqlsp/src/diagnostics.ts
packages/graphqlsp/src/persisted.ts
packages/graphqlsp/src/quickInfo.ts

> [!NOTE]
> Marking this as a `minor` since we already have minor changes queued up and some of the API signatures have changed slightly.
This aims to reduce the amount of separate `templates.has` based checks and introduce a new check that can also detect `gql.tada` via the `TypeChecker` as a fallback if the name (or expression) of `graphql()` calls is non-standard.
- Add `checks.ts` for all predicates
- Detect `graphql()` calls by checking `!!graphql.scalar` and `!!graphql.persisted` via the typ e checker
- This works even if `graphql` itself is not an identifier (any expression)
- This works even if `graphql` is renamed (more relevant now due to multi-schema support)
- Detect `graphql.persisted()` calls with the above logic
- Extract logic to detect GraphQL calls and GraphQL tagged …

patch: Increase support of harder to detect `gql.tada` API usage patterns

---

.changeset/warm-chefs-tan.md
packages/graphqlsp/package.json
pnpm-lock.yaml

See https://github.com/0no-co/gql.tada/pull/282
This marks `graphql` as a peer dependency and expands its range to accept `^15.8` and `^17` (the latter for future support).
Since we're marking it as both a dependency and a peer dependency, on package managers that don't auto-install peers, no warning should in theory be issued, while still sharing dependencies.

patch: Mark `graphql` as a peer dependency

---

.changeset/tough-crabs-heal.md
packages/example-tada/src/index.tsx
packages/graphqlsp/src/ast/index.ts
packages/graphqlsp/src/ast/resolve.ts
packages/graphqlsp/src/index.ts

This adds support for inline defined graphql-strings, auto-complete and quick-info always worked however diagnostics/... did not.
```js
useQuery({ query: graphql(``) })
```
This is slightly less performant as we traverse deeper but seems worth it
Fixes #316

fix(lsp): nested call expressions

---

.changeset/weak-fans-behave.md
packages/graphqlsp/package.json
pnpm-lock.yaml

Relevant changes:
- https://github.com/0no-co/gql.tada/releases/tag/%40gql.tada%2Finternal%401.0.0
- https://github.com/0no-co/gql.tada/releases/tag/%40gql.tada%2Finternal%400.4.0

chore: Bump `@gql.tada/internal` to `v1.0.0`

---

.changeset/small-toys-bow.md
packages/graphqlsp/src/persisted.ts

fix(persisted): use full resolved text in hash

---

.changeset/fifty-mangos-doubt.md
packages/graphqlsp/src/diagnostics.ts
packages/graphqlsp/src/persisted.ts

Fixes https://github.com/0no-co/GraphQLSP/issues/329
Brings us more inline by using unrolltadafragment

fix(persisted): nested persisted operation resolution

---

.changeset/dry-moose-camp.md
packages/graphqlsp/src/ast/checks.ts
packages/graphqlsp/src/ast/index.ts
packages/graphqlsp/src/ast/resolve.ts
packages/graphqlsp/src/ast/token.ts
packages/graphqlsp/src/autoComplete.ts
packages/graphqlsp/src/checkImports.ts
packages/graphqlsp/src/diagnostics.ts
packages/graphqlsp/src/fieldUsage.ts
packages/graphqlsp/src/graphql/getFragmentSpreadSuggestions.ts
packages/graphqlsp/src/persisted.ts
packages/graphqlsp/tsconfig.json
tsconfig.json

Updates tsconfig to enable `noUncheckedIndexedAccess`.
This is because there's several cases where it's hard to keep track of where the AST could have an optional entry in an array, that was previously assumed to exist, e.g. function arguments.
This enables this option then addresses all errors to eliminate crashes where we previously didn't check arrays on the TS AST.

fix(graphqlsp): Fix unchecked index accesses

---

.changeset/stale-plums-prove.md
packages/graphqlsp/src/persisted.ts

fix: deduplicate fragments when generating persisted document hash

---

.changeset/metal-seals-swim.md
packages/graphqlsp/src/graphql/getSchema.ts

When using the unused field detection feature without utilising the introspection generation an error is added to the diagnostics. 
This is because the code tries to save an introspection file even when the provided output path is undefined.
I have made this small fix to stop the plugin from trying to save an introspection file when the output path is undefined.
This is relevant to me, because in the Project i am working on we use other ways of generating typescript files but want to use the unused field detection and autocompletion. This works fine in the IDE, but when reading the diagnostics of typescript in the CLI to create a pipeline that ensures every field is used, we also get an error about an unsupported file type for the introspection output path (Thrown in …

fix(graphqlsp): Fix wrong fileType diagnostic error when introspection is disabled

---

.changeset/fuzzy-scissors-appear.md
packages/graphqlsp/src/ast/index.ts

Resolve https://github.com/0no-co/gql.tada/issues/374
Two loops can occur when resolving fragments:
- Loops between mutual fragments
- Loops when resolving an identifier
The first one is mostly to prevent crashes, but is already invalid and will lead to invalid behaviour. This occurs when two references reference each other. If TypeScript happens to still be able to resolve this condition, then we'd infinitely jump between the two fragments. This is easily prevented by keeping a `WeakSet` of `Identifier`s.
The second condition — which is more common in valid code — happens in scenarios when resolving an identifier leads back to this same identifier. I'm not 100% sure when this happens, but it's easily prevented.
I separated the fragment resolution into two parts to make the issue stand …

fix(graphqlsp): Fix infinite loop conditions when resolving fragments

---

.changeset/fluffy-rabbits-shake.md
packages/graphqlsp/src/persisted.ts

Resolves https://github.com/0no-co/gql.tada/issues/387
Relates to https://github.com/0no-co/gql.tada/pull/388
This guarantees correctness as the API won't know about this directive

fix: Strip the unmask directive

---

.changeset/beige-queens-worry.md
packages/graphqlsp/src/fieldUsage.ts
test/e2e/fixture-project-tada/introspection.d.ts
test/e2e/fixture-project-unused-fields/fixtures/chained-usage.ts
test/e2e/fixture-project-unused-fields/fixtures/gql/gql.ts
test/e2e/fixture-project-unused-fields/fixtures/gql/graphql.ts
test/e2e/unused-fieds.test.ts

Fixes https://github.com/0no-co/GraphQLSP/issues/353
The AST when we are dealing with nested scopes looks like the following
```
VariableDeclaration --> CallExpression --> PropertyAccessExpression --> CallExpression --> PropertyAccessExpression
```
The solution we implement here will keep looking for nested `CallExpression` and traverse them.
Note that I haven't been able to test this yet and that this is mainly a conceptual solution, I'm intending to test this out before merging 😅

fix(field-usage): Crawl chained scopes

---

.changeset/clean-doors-move.md
packages/graphqlsp/src/diagnostics.ts

Fixes https://github.com/0no-co/GraphQLSP/issues/346

Remove missing operation name

---

.changeset/upset-hats-remain.md
README.md
packages/graphqlsp/README.md
packages/graphqlsp/src/diagnostics.ts
packages/graphqlsp/src/index.ts

Resolves https://github.com/0no-co/GraphQLSP/issues/367
In `urql` you can create custom-directives that have their own behaviour, to support this we allow the user to specify their own `clientDirectives`

Allow specifying clientDirectives option
