.vscode/launch.json
package.json
packages/example/package.json
packages/graphqlsp/package.json
pnpm-lock.yaml
scripts/build.mjs
scripts/launch-debug.sh

- Added `pnpm dev` script to watch and build
- Only minify when it's _not_ a dev build
- Move `example` to pnpm
- Got breakpoints working again:
https://user-images.githubusercontent.com/571589/232288373-11fee4f0-8781-400f-8ab1-2a7487385868.mp4
_Resolves: #21_

Add dev watch build

---

.prettierignore
test/e2e/fixture-project/fixtures/simple.ts
test/e2e/fixture-project/schema.graphql
test/e2e/graphqlsp.test.ts
test/e2e/smoke.test.ts

chore: add tests for hovering and suggestions

---

packages/graphqlsp/src/index.ts

Allows to change the operation name without the type import appended at the end instead of being replaced.
https://user-images.githubusercontent.com/571589/232536848-8e52e9dd-daad-4766-9dc7-7df568dd65f6.mp4
Will look into how to e2e test this
Fixes #17

Support changing operationName

---

.changeset/pink-papayas-relax.md
.github/workflows/ci.yaml
.github/workflows/release.yaml
packages/example/src/index.generated.ts
packages/example/src/index.ts
packages/graphqlsp/src/diagnostics.ts
pnpm-lock.yaml

support updating multiple operations

---

.changeset/stupid-cobras-boil.md
packages/example/src/Pokemon.generated.ts
packages/example/src/Pokemon.ts
packages/example/src/index.generated.ts
packages/example/src/index.ts
packages/graphqlsp/src/ast/index.ts
packages/graphqlsp/src/ast/resolve.ts
packages/graphqlsp/src/autoComplete.ts
packages/graphqlsp/src/quickInfo.ts
pnpm-lock.yaml

fixes https://github.com/0no-co/GraphQLSP/issues/74

fix preceding fragments offsetting quick-info

---

.changeset/new-pens-think.md
packages/example/src/index.ts
packages/graphqlsp/src/autoComplete.ts
test/e2e/combinations.test.ts
test/e2e/fixture-project/fixtures/Combination.ts

account for offsets in suggestions

---

.changeset/quiet-fishes-suffer.md
packages/example/__generated__/baseGraphQLSP.ts
packages/example/src/index.generated.ts
packages/example/src/index.ts
packages/graphqlsp/package.json
pnpm-lock.yaml

Also trying some updates to GraphQL Code Generator

chore: add missing typed document node dep

---

.changeset/moody-clocks-approve.md
packages/example/src/index.ts
packages/graphqlsp/package.json
packages/graphqlsp/src/diagnostics.ts
packages/graphqlsp/src/graphql/getSchema.ts
pnpm-lock.yaml

While dogfooding this at Stellate we noticed that when a lot of files were open the performance would tank quite hard 😅 
Resolves #103

chore(perf): add caching for diagnostics

---

.changeset/beige-worms-joke.md
packages/graphqlsp/src/diagnostics.ts

fixes https://github.com/0no-co/GraphQLSP/issues/129

fix: update cache key to include fragments with call expressions

---

.changeset/strange-pans-clap.md
packages/graphqlsp/src/ast/token.ts
packages/graphqlsp/src/autoComplete.ts
test/e2e/fixture-project-client-preset/fixtures/fragment.ts

I guess the issue will be located in `getToken()` but will check this out later 😅 
I realise what the issue is....
When we are at index 0 of an empty line we see the line as empty because the only character (\n) is gone and we only account for that after the fact
Fixes #190

test: try out cursor changes for issue #190

---

.changeset/lemon-snakes-bow.md
packages/graphqlsp/README.md
packages/graphqlsp/src/fieldUsage.ts

feat: allow adding more reserved keys for field usage tracking

---

.changeset/beige-falcons-sneeze.md
packages/graphqlsp/src/diagnostics.ts

See: https://github.com/0no-co/gql.tada/pull/31

fix: Add `@_unmask` to supported client directives

---

.changeset/spotty-dots-greet.md
packages/graphqlsp/src/ast/token.ts

fixes #190 
This worked on Windows but not on unix 😅

fix: test token-pos change

---

.changeset/fifty-kids-walk.md
packages/graphqlsp/src/diagnostics.ts

Fixes https://github.com/0no-co/GraphQLSP/issues/211

chore: add more builtin urql directives

---

.changeset/big-spiders-itch.md
packages/example-tada/src/Pokemon.tsx
packages/graphqlsp/src/ast/token.ts
packages/graphqlsp/src/diagnostics.ts

fix: offset issue w/ graphql syntax annotation

---

.changeset/cyan-guests-share.md
packages/example-tada/introspection.ts
packages/example-tada/src/index.tsx
packages/graphqlsp/src/checkImports.ts

fix: only warn for exported fragments

---

packages/graphqlsp/src/diagnostics.ts
packages/graphqlsp/src/index.ts

I've noticed that the tsserver sometimes runs plugins for multiple workspace entries... but not all the time, it seems to sometimes get into this weird state after a while.

bail when we see the lsp ran already

---

.changeset/silent-gorillas-knock.md
packages/example-tada/introspection.ts
packages/graphqlsp/package.json

fix: Write ESM build output to .mjs

---

.changeset/thin-fishes-fry.md
package.json
packages/example-tada/introspection.ts
packages/graphqlsp/src/fieldUsage.ts
test/e2e/unused-fieds.test.ts
tsconfig.json

This will bubble up unused fields to their closest parent and combine it

feat: bubble up unused parents

---

.changeset/chilly-coins-end.md
packages/graphqlsp/src/ast/token.ts
packages/graphqlsp/src/autoComplete.ts
test/e2e/fixture-project-tada/fixtures/type-condition.ts
test/e2e/fixture-project-tada/introspection.d.ts
test/e2e/tada.test.ts

fix: support suggestions in type-conditions

---

.changeset/rotten-stingrays-kick.md
packages/graphqlsp/src/ast/index.ts
packages/graphqlsp/src/ast/resolve.ts

Fixes https://github.com/0no-co/GraphQLSP/issues/270

fix(lsp): prevent crash with empty list of definitions

---

.changeset/silent-falcons-explode.md
packages/graphqlsp/src/ast/checks.ts

Resolves https://github.com/0no-co/gql.tada/issues/331

fix(graphqlsp): Fix unexpected `undefined` when checking persisted call

---

.changeset/flat-boats-approve.md
packages/graphqlsp/src/ast/token.ts
packages/graphqlsp/src/autoComplete.ts

Fixes https://github.com/0no-co/GraphQLSP/issues/268

chore(lsp): Avoid suggestions leading up to a fragment-spread

---

.changeset/silent-spiders-tell.md
packages/graphqlsp/src/persisted.ts

Fixes https://github.com/0no-co/GraphQLSP/issues/359

Extract fragment definitions from the root-document
